# PRIMA PROVA DI NEURAL NETWORK

### importazioni

In [1]:
import sys
sys.path.append("../ML_app")

from neural_network import SGD_algorithm, neural_predict
from cost_functions import sigmoide

In [2]:
import pickle as pkl
import numpy as np

with open('data/ottani_NIR.pkl', 'rb') as f:
    dizionario = pkl.load(f)
    
# dati train
train_ones = dizionario['train']['NIR']['ones']
train_zeros = dizionario['train']['NIR']['zeros']
train_labels = dizionario['train']['labels']
train_x = np.concatenate((train_zeros, train_ones))

# dati test
test_ones = dizionario['test']['NIR']['ones']
test_zeros = dizionario['test']['NIR']['zeros']
test_labels = dizionario['test']['labels']
test_x = np.concatenate((test_zeros, test_ones))

In [3]:
'''
SGD_algorithm(
    weights: np.ndarray, 
    inputs: np.ndarray,
    expected_output: np.ndarray,
    learning_rate: float = 0.9,
)
'''
# inputs sono i train_x, expected outputs sono i train_labels

'\nSGD_algorithm(\n    weights: np.ndarray, \n    inputs: np.ndarray,\n    expected_output: np.ndarray,\n    learning_rate: float = 0.9,\n)\n'

## SENZA PCA

In [4]:
# inizializzazione weights
N = train_x.shape[1]
weights = np.random.rand(N)

In [5]:
weights

array([0.06703293, 0.36573752, 0.07704988, 0.01920105, 0.83651937,
       0.38793908, 0.68763209, 0.60075614, 0.08374859, 0.5873919 ,
       0.75214371, 0.9685043 , 0.05730183, 0.1022787 , 0.59965497,
       0.79102965, 0.45428392, 0.93258436, 0.37235339, 0.30642521,
       0.71101609, 0.18528109, 0.14888252, 0.11931946, 0.99474549,
       0.97070317, 0.11570571, 0.79218416, 0.74886123, 0.99272616,
       0.7439213 , 0.19357776, 0.62844407, 0.26792747, 0.29097534,
       0.40886148, 0.84579724, 0.13360575, 0.78820939, 0.39146364,
       0.36703094, 0.5807037 , 0.69343695, 0.3608586 , 0.43097951,
       0.90794963, 0.95298584, 0.76181107, 0.50761869, 0.36814988,
       0.12292653, 0.11836271, 0.02217969, 0.66247   , 0.87638367,
       0.57752726, 0.74356585, 0.95368233, 0.2232452 , 0.32517755,
       0.60609172, 0.33746908, 0.52823962, 0.40953065, 0.42038164,
       0.12434059, 0.45599917, 0.12775609, 0.30950212, 0.63919325,
       0.54169189, 0.98982288, 0.09407842, 0.72598684, 0.56611

### normalizzazione

In [6]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = MinMaxScaler()
train_x = scaler.fit_transform(train_x, train_labels)
test_x = scaler.transform(test_x)

### training

In [7]:
epoche = 100

for i in range(epoche):
    weights = SGD_algorithm(
        weights,
        train_x,
        train_labels,
        learning_rate = 0.5
    )

In [8]:
weights

array([0.06703293, 0.36573752, 0.07704988, 0.01920105, 0.83651937,
       0.38793908, 0.68763209, 0.60075614, 0.08374859, 0.5873919 ,
       0.75214371, 0.9685043 , 0.05730183, 0.1022787 , 0.59965497,
       0.79102965, 0.45428392, 0.93258436, 0.37235339, 0.30642521,
       0.71101609, 0.18528109, 0.14888252, 0.11931946, 0.99474549,
       0.97070317, 0.11570571, 0.79218416, 0.74886123, 0.99272616,
       0.7439213 , 0.19357776, 0.62844407, 0.26792747, 0.29097534,
       0.40886148, 0.84579724, 0.13360575, 0.78820939, 0.39146364,
       0.36703094, 0.5807037 , 0.69343695, 0.3608586 , 0.43097951,
       0.90794963, 0.95298584, 0.76181107, 0.50761869, 0.36814988,
       0.12292653, 0.11836271, 0.02217969, 0.66247   , 0.87638367,
       0.57752726, 0.74356585, 0.95368233, 0.2232452 , 0.32517755,
       0.60609172, 0.33746908, 0.52823962, 0.40953065, 0.42038164,
       0.12434059, 0.45599917, 0.12775609, 0.30950212, 0.63919325,
       0.54169189, 0.98982288, 0.09407842, 0.72598684, 0.56611

### testing

In [9]:
prediction = neural_predict(
    weights,
    test_x
)

In [10]:
prediction

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---

## neural network con PCA

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=7)
train_x_pca = pca.fit_transform(train_x, train_labels)

### training

In [12]:
# inizializzo weights nuovi
N_pca = train_x_pca.shape[1]
weights_pca = np.random.rand(N_pca)

In [13]:
epoche = 10_000

for i in range(epoche):
    weights_pca = SGD_algorithm(
        weights_pca,
        train_x_pca,
        train_labels,
        learning_rate = 0.9
    )

### test

In [14]:
test_x_pca = pca.transform(test_x)

In [15]:
prediction = neural_predict(
    weights_pca,
    test_x_pca
)

In [16]:
prediction

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.])